#spring:
#  security:
#    user:
#      password: 1111

spring:
  datasource:
    url: jdbc:mysql://localhost:53306/spring_security
    username: root
  jpa:
    hibernate:
#      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.security: trace
    org.hibernate:
      SQL: debug
      orm.jdbc.bind: trace